#include <stdint.h>

#ifndef STATS_HTML_C
#define STATS_HTML_C
const uint8_t STATS_HTML[] = {

"<!DOCTYPE html>\n"
"<html>\n"
"   <head>\n"
"       <title>LEMON STATS DASHBOARD</title>\n"
"       <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"       <link rel=\"icon\" type=\"image/png\" href=\"favicon.png\">\n"
"   <style>\n"
"       html {\n"
"           font-family: Arial, Helvetica, sans-serif;\n"
"           display: inline-block;\n"
"           text-align: center;\n"
"       }\n"
"       h1 {\n"
"           font-size: 1.8rem;\n"
"           color: white;\n"
"       }\n"
"       .topnav {\n"
"           overflow: hidden;\n"
"           background-color: #0A1128;\n"
"       }\n"
"       body {\n"
"           margin: 0;\n"
"       }\n"
"       .content {\n"
"           padding: 50px;\n"
"       }\n"
"       .card-grid {\n"
"           max-width: 800px;\n"
"           margin: 0 auto;\n"
"           display: grid;\n"
"           grid-gap: 2rem;\n"
"           grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n"
"       }\n"
"       .card {\n"
"           background-color: white;\n"
"           box-shadow: 2px 2px 12px 1px rgba(140,140,140,.5);\n"
"       }\n"
"       .card-title {\n"
"           font-size: 1.2rem;\n"
"           font-weight: bold;\n"
"           color: #034078\n"
"       }\n"
"       .reading {\n"
"           font-size: 1.2rem;\n"
"           color: #1282A2;\n"
"       }\n"
"       .button {\n"
"           display: inline-block;\n"
"           padding: 10px 20px;\n"
"           margin: 10px;\n"
"           font-size: 18px;\n"
"           cursor: pointer;\n"
"           border: none;\n"
"           border-radius: 5px;\n"
"           transition: background-color 0.3s;\n"
"       }\n"
"       .button-active {\n"
"           background-color: #2980b9 !important;\n"
"           color: #fff;\n"
"       }\n"
"       .button-red {\n"
"           background-color: #e74c3c;\n"
"           color: #fff;\n"
"       }\n"
"       .button-orange {\n"
"           background-color: #e67e22;\n"
"           color: #fff;\n"
"       }\n"
"       .button-green {\n"
"           background-color: #2ecc71;\n"
"           color: #fff;\n"
"       }\n"
"       .button-blue {\n"
"           background-color: #3498db;\n"
"           color: #fff;\n"
"       }\n"
"   </style>\n"
"   </head>\n"
"   <body>\n"
"       <div class=\"topnav\">\n"
"           <h1>LEMON STATISTICS</h1>\n"
"       </div>\n"
"       <div class=\"content\">\n"
"           <button class=\"button button-green\" id=\"updateButton\">Update</button>\n"
"           <button class=\"button button-red\" id=\"rebootButton\">Reboot</button>\n"
"           <div class=\"card-grid\">\n"
"               <div class=\"card\">\n"
"                   <p class=\"card-title\">Fixes</p>\n"
"                   <p class=\"reading\"><span id=\"fixCount\"></span></p>\n"
"               </div>\n"
"               <div class=\"card\">\n"
"                   <p class=\"card-title\">Good Uplinks</p>\n"
"                   <p class=\"reading\"><span id=\"goodUplinkMessageCount\"></span></p>\n"
"               </div>\n"
"               <div class=\"card\">\n"
"                   <p class=\"card-title\">Good MQTTs</p>\n"
"                   <p class=\"reading\"><span id=\"privateMQTTUploadCount\"></span></p>\n"
"               </div>\n"
"               <div class=\"card\">\n"
"                   <p class=\"card-title\">Bad Uplink %</p>\n"
"                   <p class=\"reading\"><span id=\"uplinkBadMessagePercentage\"></span> %</p>\n"
"               </div>\n"
"               <div class=\"card\">\n"
"                   <p class=\"card-title\">Bad Uplinks</p>\n"
"                   <p class=\"reading\"><span id=\"badUplinkMessageCount\"></span></p>\n"
"               </div>\n"
"               <div class=\"card\">\n"
"                   <p class=\"card-title\">Bad Length Uplinks</p>\n"
"                   <p class=\"reading\"><span id=\"badLengthUplinkMsgCount\"></span></p>\n"
"               </div>\n"
"               <div class=\"card\">\n"
"                   <p class=\"card-title\">Bad Checksum Uplinks</p>\n"
"                   <p class=\"reading\"><span id=\"badChkSumUplinkMsgCount\"></span></p>\n"
"               </div>\n"
"               <div class=\"card\">\n"
"                   <p class=\"card-title\">Missing Uplinks</p>\n"
"                   <p class=\"reading\"><span id=\"uplinkMessageMissingCount\"></span></p>\n"
"               </div>\n"
"               <div class=\"card\">\n"
"                   <p class=\"card-title\">Lemon Uptime</p>\n"
"                   <p class=\"reading\"><span id=\"lemonUptime\"></span></p>\n"
"               </div>\n"
"           </div>\n"
"       </div>\n"
"        <iframe src=\"/webserial\" width=\"1000\" height=\"1000\" frameborder=\"0\"></iframe>\n"
"       <script>\n"
"       var gateway = `ws://${window.location.hostname}/ws`;\n"
"       var websocket;\n"
"       // Init web socket when the page loads\n"
"       window.addEventListener('load', onload);\n"
"       function onload(event) {\n"
"           initWebSocket();\n"
"       }\n"
"       function getReadings(){\n"
"           websocket.send(\"getReadings\");\n"
"       }\n"
"       function initWebSocket() {\n"
"           console.log('Trying to open a WebSocket connection…');\n"
"           websocket = new WebSocket(gateway);\n"
"           websocket.onopen = onOpen;\n"
"           websocket.onclose = onClose;\n"
"           websocket.onmessage = onMessage;\n"
"       }\n"
"       // When websocket is established, call the getReadings() function\n"
"       function onOpen(event) {\n"
"           console.log('Connection opened');\n"
"           getReadings();\n"
"       }\n"
"       function onClose(event) {\n"
"           console.log('Connection closed');\n"
"           setTimeout(initWebSocket, 2000);\n"
"       }\n"
"       // Function that receives the message from the ESP32 with the readings\n"
"       function onMessage(event) {\n"
"           console.log(event.data);\n"
"           var myObj = JSON.parse(event.data);\n"
"           var keys = Object.keys(myObj);\n"
"           for (var i = 0; i < keys.length; i++){\n"
"               var key = keys[i];\n"
"               document.getElementById(key).innerHTML = myObj[key];\n"
"           }\n"
"       }\n"
"       // Function to handle button activation\n"
"       function activateButton(buttonId) {\n"
"           var button = document.getElementById(buttonId);\n"
"           button.classList.add(\"button-active\");\n"
"           setTimeout(function() {\n"
"               button.classList.remove(\"button-active\");\n"
"           }, 100);\n"
"       }\n"
"       // Function to send a POST request\n"
"       function sendPostRequest(url, buttonId) {\n"
"           activateButton(buttonId);\n"
"           fetch(url, {\n"
"               method: 'POST',\n"
"               headers: {\n"
"                   'Content-Type': 'application/x-www-form-urlencoded'\n"
"               },\n"
"               body: 'button=' + encodeURIComponent(buttonId)\n"
"           });\n"
"       }\n"
"       // Function to handle button clicks\n"
"       function handleButtonClick(buttonId) {\n"
"           sendPostRequest(window.location.href, buttonId);\n"
"       }\n"
"       // Function to handle update button click\n"
"       function handleUpdateButtonClick() {\n"
"           window.location.href = \"/update\";\n"
"       }\n"
"       // Attach event listener to the update button\n"
"       document.getElementById(\"updateButton\").addEventListener(\"click\", handleUpdateButtonClick);\n"
"       document.getElementById(\"rebootButton\").addEventListener(\"click\", function() {\n"
"           handleButtonClick(\"rebootButton\");\n"
"       });\n"
"       // Function to send a GET request\n"
"       function sendGetRequest(url) {\n"
"           fetch(url, {\n"
"               method: 'GET',\n"
"               headers: {\n"
"                   'Content-Type': 'text/html'\n"
"               }\n"
"           })\n"
"           .then(response => response.text())\n"
"           .then(data => document.documentElement.innerHTML = data)\n"
"           .catch(error => console.error('Error:', error));\n"
"       }\n"
"       function handleKeyDown(event) {\n"
"           switch(event.key) {\n"
"               case 'u':\n"
"                   handleUpdateButtonClick();\n"
"                   break;\n"
"           }\n"
"       }\n"
"       // Attach keydown event listener to document\n"
"       document.addEventListener(\"keydown\", handleKeyDown);\n"
"       </script>\n"
"   </body>\n"
"</html>"

};

const uint32_t STATS_HTML_SIZE = sizeof(STATS_HTML);

#endif
